### ISSUE TITLE
Question: how to compile multiple files (bundles)?

### ISSUE THREAD

**Issue by slavafomin** [backflip/gulp-resolve-dependencies#11]
Hello!

Is there an obvious way to compile multiple bundles?

I have the following code:

```javascript
gulp.task('build:scripts', function buildScripts () {
  return gulp
    .src('scripts/*.js')
    .pipe(resolveDependencies({
      pattern: /\* @require [\s-]*(.*?\.js)/g,
      log: true
    }))
    .pipe(concat('bundle.js'))
    .pipe(gulp.dest(pathModule.join(targetDir, 'js')))
  ;
});
```

`concat()` merges all source script files together into a single destination file. However, I want to preserve original files, but to resolve dependencies for each of them. Is it possible to do it fluently?

Thank you!

**Comment by backflip** [comment]
If I understand you correctly, you could use something like [gulp-foreach](https://www.npmjs.com/package/gulp-foreach):

```js
var gulp = require('gulp'),
  resolveDependencies = require('gulp-resolve-dependencies')),
  foreach = require('gulp-foreach');

gulp.task('build:scripts', function buildScripts () {
  return gulp.src('scripts/*.js')
    .pipe(foreach(function (stream, file) {
      return stream
        .pipe(resolveDependencies({
          pattern: /\* @require [\s-]*(.*?\.js)/g,
          log: true
        }))
        .pipe(concat(file.name));
    }))
    .pipe(gulp.dest('dist'));
});

**Comment by slavafomin** [comment]
Thank you @backflip, that looks like a nice solution! I will give it a try. I think you should add it to the documentation of the module cause it probably a solid use-case.
