### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Nashorn** [backflip/gulp-resolve-dependencies#13]
This plugin is not working. It creates a copy of my src in the dest directory and does not resolve any dependencies.

Here is my task:

```javascript
gulp.task('js', function(){
  gulp.src(['js/main.js'])
    .pipe(resolveDependencies({
      pattern: /\* @requires [\s-]*(.*\.js)/g,
      log:true,
      ignoreCircularDependencies:true
    }))
        .on('error', function(err) {
            console.log(err.message);
        })
    .pipe(gulp.dest('dist/builds/js/'));
});
```

Here is my main.js:
```javascript
/**
 * 	@requires libs/jquery/jquery.js
	@requires test.js
 */


 function main(){
	alert("main")
}
```

And yes, I do have main.js and test.js inside /js folder. And i do have a /libs inside /js as well.

* /js
      * /libs
          * /jquery
              * jquery.js
* main.js
* test.js

**Comment by backflip** [comment]
Could you check your `@requires` declarations? Your pattern specifies them as `* @requires …`:

```js
/**
 * @requires libs/jquery/jquery.js
 * @requires test.js
 */

function main(){
    alert("main")
}
```

**Comment by backflip** [comment]
Closed due to inactivity. Feel free to re-open if the problem persists.
