### ISSUE TITLE
Example for resolving react from just node modules

### ISSUE THREAD

**Issue by nitish24p** [backflip/gulp-resolve-dependencies#17]
I am trying to resolve the install of react to only the version in my node_modules using gulp. The code below is my browserify command. Can you tell me whats wrong with the code.

```javascript
var resolveDependencies = require('gulp-resolve-dependencies');
var babelify = require('babelify');

function reactBrowserify(path, fileName) {
    if (params.env === 'prod') {
        process.env.NODE_ENV = 'production';
    }
    browserify(path)
    .on("error", function(err) {
      this.emit('end');
    })
    .resolveDependencies({
        resolvePath: {'react'}
    })
    .transform("babelify", {presets: ["es2015", "react"]})
    .bundle()
    .pipe(source(fileName))
    .pipe(buffer())
    .pipe(gulpif(params.env === 'prod', uglify()))
    .pipe(gulp.dest('./web/build/js'));
}
```

However i still see that 2 versions of react are being installed as i get that error in my browser. Can someone help me out here

**Comment by backflip** [comment]
@nitish24p, if you are using Browserify, you don't need this plugin. Doing something like `var React = require('react');` will already make Browserify resolved and include the dependency.
