### ISSUE TITLE
should emit errors if there is any circular dependency

### ISSUE THREAD

**Issue by huang47** [backflip/gulp-resolve-dependencies#6]
Currently it skips the file if it's previously added. will commit a PR to support this behavior

**Comment by backflip** [comment]
Thanks a lot for this. [v1.1.0](https://github.com/backflip/gulp-resolve-dependencies/releases/tag/v1.1.0) adds a new option ```ignoreCircularDependencies``` which is set to ```false``` from [v2.0.0](https://github.com/backflip/gulp-resolve-dependencies/releases/tag/v2.0.0) onwards.
